local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()

local Window = OrionLib:MakeWindow({Name = "ooga booga hub", HidePremium = true, SaveConfig = false, ConfigFolder = "OrionTest"})

local Main = Window:MakeTab({
	Name = "Main",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

Main:AddButton({
	Name = "Inf Money",
	Callback = function()
        -- Script generated by SimpleSpy - credits to exx#9394

        local args = {
            [1] = -9e1000,
            [2] = false,
            [3] = "food"
        }

        game:GetService("ReplicatedStorage").changeCash:FireServer(unpack(args))

  	end    
})